name: Diablo 4 Data Scraper

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Controlla il codice nel repository
      uses: actions/checkout@v4

    - name: Recupera dati aggiornati sui timer
      run: |
        # Scarica i dati puliti direttamente dall'API alternativa stabili
        curl -s "https://api.d4gg.io/v1/events" -o data.json

    - name: Salva e pubblica i dati aggiornati
      run: |
        git config --global user.name "D4TrackerBot"
        git config --global user.email "bot@d4tracker.local"
        git add data.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Aggiornamento automatico timer D4" && git push)
